//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookstoreApp.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_BookStore
    {
        public long BookId { get; set; }
        public string BookName { get; set; }
        public string AuthorName { get; set; }
        public string BookPublication { get; set; }
        public Nullable<System.DateTime> BookDate { get; set; }
        public string BookISBN { get; set; }
        public string BookDescription { get; set; }
        public Nullable<decimal> BookPrice { get; set; }
        public string BookPic { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    }
}
